name: unit-tests
on:
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - Makefile
      - go.mod
      - go.sum

jobs:
  unit-tests:
    name: make test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "1.13.x"
          - "1.14.x"
          - "1.15.x"
          - "1.16.x"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: make test
        run: make test